### PR TITLE
generated code should not violate wartremover checks

### PR DESCRIPTION
**Pull request by bjaglin**
`circe-derivation` triggers [wartremover](https://github.com/wartremover/wartremover)'s `Product`/`Serializable` warts when deriving case classes that have heterogeneous attribute types (so most of them).

```
  case class A(i: Integer)
  implicit val decodeA: Decoder[A] = deriveDecoder

  case class B(i: Integer)
  implicit val decodeB: Decoder[B] = deriveDecoder

  final case class ProductSerializable(
      a: A,
      bs: List[B]
  )
  implicit val decodeProductSerializable: Decoder[ProductSerializable] = deriveDecoder
```

```
--- <unnamed>
+++ <unnamed>
@@ -1,27 +1,14 @@
           else
             res.asInstanceOf[io.circe.Decoder.Result[testcase.ProductSerializable]]
         };
-        private[this] def errors(results: List[io.circe.AccumulatingDecoder.Result[_]]): List[io.circe.DecodingFailure] = collection.this.TraversableOnce.flattenTraversableOnce[io.circe.DecodingFailure, List](results.iterator.collect[List[io.circe.DecodingFailure]](({
-          @SerialVersionUID(value = 0) final <synthetic> class $anonfun extends scala.runtime.AbstractPartialFunction[io.circe.AccumulatingDecoder.Result[_],List[io.circe.DecodingFailure]] with Serializable {
-            def <init>(): <$anon: io.circe.AccumulatingDecoder.Result[_] => List[io.circe.DecodingFailure]> = {
-              $anonfun.super.<init>();
-              ()
-            };
-            final override def applyOrElse[A1 <: io.circe.AccumulatingDecoder.Result[_], B1 >: List[io.circe.DecodingFailure]](x6: A1, default: A1 => B1): B1 = ((x6.asInstanceOf[io.circe.AccumulatingDecoder.Result[_]]: io.circe.AccumulatingDecoder.Result[_]): io.circe.AccumulatingDecoder.Result[_$6] @unchecked) match {
-              case (e: cats.data.NonEmptyList[io.circe.DecodingFailure])cats.data.Validated.Invalid[cats.data.NonEmptyList[io.circe.DecodingFailure]]((errors @ _)) => errors.toList
-              case (defaultCase$ @ _) => default.apply(x6)
-            };
-            final def isDefinedAt(x6: io.circe.AccumulatingDecoder.Result[_]): Boolean = ((x6.asInstanceOf[io.circe.AccumulatingDecoder.Result[_]]: io.circe.AccumulatingDecoder.Result[_]): io.circe.AccumulatingDecoder.Result[_$6] @unchecked) match {
-              case (e: cats.data.NonEmptyList[io.circe.DecodingFailure])cats.data.Validated.Invalid[cats.data.NonEmptyList[io.circe.DecodingFailure]]((errors @ _)) => true
-              case (defaultCase$ @ _) => false
-            }
-          };
-          new $anonfun()
-        }: PartialFunction[io.circe.AccumulatingDecoder.Result[_],List[io.circe.DecodingFailure]])))(scala.Predef.$conforms[List[io.circe.DecodingFailure]]).flatten.toList;
+        private[this] def errors(result: io.circe.AccumulatingDecoder.Result[_]): List[io.circe.DecodingFailure] = result match {
+          case (a: _$6)cats.data.Validated.Valid[_$6](_) => scala.collection.immutable.Nil
+          case (e: cats.data.NonEmptyList[io.circe.DecodingFailure])cats.data.Validated.Invalid[cats.data.NonEmptyList[io.circe.DecodingFailure]]((e @ _)) => e.toList
+        };
         final override def decodeAccumulating(c: io.circe.HCursor): io.circe.AccumulatingDecoder.Result[testcase.ProductSerializable] = {
           val res1: io.circe.AccumulatingDecoder.Result[testcase.A] = $anon.this.decoder0.tryDecodeAccumulating(c.downField("a"));
           val res2: io.circe.AccumulatingDecoder.Result[List[testcase.B]] = $anon.this.decoder1.tryDecodeAccumulating(c.downField("bs"));
-          val dfs: List[io.circe.DecodingFailure] = $anon.this.errors(scala.collection.immutable.List.apply[cats.data.Validated[cats.data.NonEmptyList[io.circe.DecodingFailure],Product with Serializable]](res1, res2));
+          val dfs: List[io.circe.DecodingFailure] = scala.collection.immutable.List.apply[List[io.circe.DecodingFailure]]($anon.this.errors(res1), $anon.this.errors(res2)).flatten[io.circe.DecodingFailure](scala.Predef.$conforms[List[io.circe.DecodingFailure]]);
           if (dfs.isEmpty)
             cats.data.Validated.valid[cats.data.NonEmptyList[io.circe.DecodingFailure], testcase.ProductSerializable](new testcase.ProductSerializable(res1.asInstanceOf[cats.data.Validated.Valid[testcase.A]].a, res2.asInstanceOf[cats.data.Validated.Valid[List[testcase.B]]].a))
           else
```

### CODE REVIEW

**Comment by bjaglin** [comment]
Puzzled by
```
Caused by: java.lang.ClassCastException: scala.collection.immutable.Nil$ cannot be cast to cats.data.Validated$Valid
	at io.circe.derivation.annotations.jsoncodecmacrossuiteaux.SelfRecursiveWithOption$$anon$17.decodeAccumulating(JsonCodecMacrosSuite.scala:106)
	at io.circe.AccumulatingDecoder$$anon$7.apply(AccumulatingDecoder.scala:72)
	at io.circe.testing.CodecLaws$class.codecAccumulatingConsistency(CodecTests.scala:20)
	at io.circe.testing.CodecLaws$$anon$2.codecAccumulatingConsistency(CodecTests.scala:24)
	at io.circe.testing.CodecTests$$anonfun$codec$4.apply(CodecTests.scala:46)
	at io.circe.testing.CodecTests$$anonfun$codec$4.apply(CodecTests.scala:45)
```

**Comment by travisbrown** [comment]
Isn't there a way to disable wartremover for synthetic / macro code? I'm happy to review this change but I think it's unlikely to get merged if it has any impact on runtime performance.

**Comment by bjaglin** [comment]
To my knowledge, there is no way to disable wartremover for macro code at the moment (see feature request https://github.com/wartremover/wartremover/issues/215).

Regarding runtime performance, it _looks_ like the version in that PR triggers less object creation, but there any bench that I can use to verify that there is no regression?

Meanwhile, I will take some time to familiarize with law testing to look at the test failure.

**Comment by travisbrown** [comment]
@bjaglin Unfortunately publishing locally and comparing circe-benchmarks with `-prof gc` to the snapshot is my current workflow. I'm happy to do that once this PR is ready. Thanks!

**Comment by bjaglin** [comment]
After many attemps, this is ready for review.
* I am new to quasiquotes so the syntax I am using might be unnecessarily verbose
* Performance-wise, if this turns out to trigger a regression, maybe I could consider reimplementing something like https://github.com/circe/circe-derivation/pull/15/files ? (which seems to have been reworked in https://github.com/circe/circe-derivation/pull/28/files) Or simply emit a `@SuppressWarnings(Array("org.wartremover.warts.Product", "org.wartremover.warts.Serializable"))` within the generated code to silence wartremover?

**Comment by travisbrown** [comment]
Thanks! This looks reasonable to me, and given that it only affects the error-accumulation case I'm not too worried about the performance implications (although we should check).

**Pull request merged**
