### PR TITLE
Compile time only

### PR DESCRIPTION
**Pull request by backuitist**
We have this situation where different team with different taste (one like circe-generic, another like circe-derivation) need to share circe codecs.
Having circe-derivation compile-time only makes it possible to define those codecs using circe-derivation without commiting (pulling one transitively) to either generic or derivation.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @backuitist!

**Comment by travisbrown** [comment]
I can go ahead and publish a new milestone tomorrow if that'd be useful, @backuitist?

**Comment by kaishh** [comment]
Eh, somewhat conflicts with our usage here (summoning circe-derivation codecs with implicit macro) https://github.com/pshirshov/izumi-r2/blob/develop/idealingua/idealingua-runtime-rpc-circe/src/main/scala/com/github/pshirshov/izumi/idealingua/runtime/circe/IRTWithCirce.scala#L8

**Comment by backuitist** [comment]
@travisbrown yes, a release would be great! Thanks!

@kaishh I don't see how this change impacts your code?

**Comment by kaishh** [comment]
@backuitist It doesn't, but merging similar code upstream would mean creating `DerivedDecoder`, `DerivedEncoder, etc. runtime classes which may possibly conflict with your usecase

**Comment by travisbrown** [comment]
@kaishh We could have a new module named circe-derivation-extras (or something better), with the contract being that everything in circe-derivation can be used as a compile-time only dependency, while circe-derivation-extras would provide a runtime API with things like a `WithCirceCodec` trait.

**Comment by backuitist** [comment]
@kaishh I don't understand what you mean by "merging similar code upstream"? What is upstream?
Why would this mean creating `DerivedDecoder` classes?

**Pull request merged**
