### PR TITLE
Fix #21, try primary constructor first if it exists

### LINKED ISSUE #21: Derivation fails if there's an .apply() method with different field names
Minimal example:

```scala
import io.circe._
import io.circe.derivation._

case class Abc(x: String)

object Abc {
  implicit val dec: Decoder[Abc] = deriveDecoder[Abc]
  implicit val enc: ObjectEncoder[Abc] = deriveEncoder[Abc]

  def apply(otherfield: Int): Abc = new Abc(otherfield.toString)
}
```
```
Error:(7, 50) No method otherfield in A$A111.this.Abc (this is probably because a constructor parameter isn't a val)
  implicit val dec: Decoder[Abc] = deriveDecoder[Abc]
                                                ^
Error:(8, 56) No method otherfield in A$A111.this.Abc (this is probably because a constructor parameter isn't a val)
  implicit val enc: ObjectEncoder[Abc] = deriveEncoder[Abc]
                                                      ^
```
But If it's `def apply(x: Int): Abc = new Abc(x)` then it works

### PR DESCRIPTION
**Pull request by kaishh**
Hi! If you accept PR, could you please release new version or snapshot on sonatype? Thanks.

### CODE REVIEW

**Comment by travisbrown** [comment]
Yes, will get this merged and released (as a new milestone) this weekend.

**Comment by kaishh** [comment]
@travisbrown 
Thank you!

**Comment by kaishh** [comment]
@travisbrown Hi, any progress?

**Comment by travisbrown** [comment]
[New milestone](https://github.com/circe/circe-derivation/releases/tag/v0.9.0-M3) is out. Apologies for the delay—there was some other work I wanted to get into this release, but I don't think it's necessary to wait for it.

**Pull request merged**
